# Generated by Django 3.1.7 on 2021-03-18 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254)),
                ('headshot', models.ImageField(upload_to='tmp', verbose_name='фотография')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Веб-страница')),
            ],
            options={
                'db_table': 'composers',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('adress', models.CharField(blank=True, db_column='addr', max_length=50, null=True, verbose_name='Адрес')),
                ('website', models.URLField(null=True, verbose_name='Веб-сайт')),
            ],
            options={
                'db_table': 'publishers',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ноты')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Дата создания муз. произведения')),
                ('publication_date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата публикации нот')),
                ('publisher', models.ForeignKey(blank=True, db_column='publisher_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.publisher', verbose_name='Издатель')),
            ],
            options={
                'db_table': 'scores',
            },
        ),
    ]
