# Generated by Django 3.1.7 on 2021-03-19 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='pen_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ComposerScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composer', models.ForeignKey(db_column='composer_id', on_delete=django.db.models.deletion.CASCADE, to='core.composer')),
                ('score', models.ForeignKey(db_column='score_id', on_delete=django.db.models.deletion.CASCADE, to='core.score')),
            ],
            options={
                'db_table': 'composers_scores',
            },
        ),
        migrations.AddField(
            model_name='score',
            name='composers',
            field=models.ManyToManyField(through='core.ComposerScore', to='core.Composer'),
        ),
    ]
