# Generated by Django 3.1.7 on 2021-03-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210321_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='tmp', verbose_name='фотография'),
        ),
    ]
