# Generated by Django 3.1.7 on 2021-03-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210319_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='composer',
            name='pen_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
