# Generated by Django 3.1.7 on 2021-03-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210317_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254)),
                ('headshot', models.ImageField(upload_to='tmp', verbose_name='фотография')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Веб-страница')),
            ],
            options={
                'db_table': 'composers',
            },
        ),
        migrations.AddField(
            model_name='publisher',
            name='website',
            field=models.URLField(null=True, verbose_name='Веб-сайт'),
        ),
        migrations.AddField(
            model_name='score',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания муз. произведения'),
        ),
        migrations.AddField(
            model_name='score',
            name='publication_date',
            field=models.DateField(null=True, verbose_name='Дата публикации нот'),
        ),
    ]
